services:
#    edu.example:
#        class: EduBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    edu.application_service_user.add_user:
        class: EduBundle\Application\Service\User\AddUser
        arguments:
            - "@edu.doctrine_user.repository"

    edu.application_service_user.list_users:
        class: EduBundle\Application\Service\User\ListUsers
        arguments:
            - "@edu.dbal_user.repository"


    edu.dbal_user.repository:
        class: EduBundle\Infrastructure\Repository\DBAL\User\UserRepository
        arguments:
            - "@doctrine.dbal.default_connection"

    edu.doctrine_user.repository:
        class: EduBundle\Infrastructure\Repository\Doctrine\User\UserRepository
        arguments:
            - "@doctrine.orm.entity_manager"

