# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    playground.application.service.user.list:
        class: Playground\App\Application\Service\User\ListUsers
        arguments: ["@playground.repository.user"]

    playground.application.service.user.add:
        class: Playground\App\Application\Service\User\AddUser
        arguments:
            - "@playground.repository.user"
        tags:
            - { name: command_handler, handles: Playground\App\Application\Service\User\AddUserCommand }

    playground.application.service.user.edit:
        class: Playground\App\Application\Service\User\EditUser
        arguments:
            - "@playground.repository.user"
        tags:
            - { name: command_handler, handles: Playground\App\Application\Service\User\EditUserCommand }

    playground.application.service.user.remove:
        class: Playground\App\Application\Service\User\RemoveUser
        arguments:
            - "@playground.repository.user"
        tags:
            - { name: command_handler, handles: Playground\App\Application\Service\User\RemoveUserCommand }

    playground.repository.user:
        alias: playground.repository.dbal.user

    playground.repository.dbal.user:
        public: false
        class: Playground\App\Infrastructure\Repository\Doctrine\User\UserDbalRepository
        arguments:
            - "@doctrine.dbal.default_connection"

    playground.domain.event_dispatcher:
        class: Playground\App\Infrastructure\MessageBus\Symfony\EventDispatcher
        arguments:
            - "@event_dispatcher"

    playground.domain.command_bus:
        class: Playground\App\Infrastructure\MessageBus\SimpleBus\CommandBus
        arguments:
            - "@command_bus"

    playground.domain.command_bus.middleware.event_aware:
        class: Playground\App\Infrastructure\MessageBus\SimpleBus\EventAwareCommandBusMiddleware
        public: false
        arguments:
            - "@playground.domain.event_dispatcher"
        tags:
            - { name: command_bus_middleware, priority: 100 }

    playground.domain.command_bus.middleware.db_transaction:
        class: Playground\App\Infrastructure\MessageBus\SimpleBus\DBTransactionalityCommandBusMiddleware
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_bus_middleware, priority: 100 }
