# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    appbundle.test_repository:
        class: AppBundle\Repository\TestRepository
        arguments:
            - "@doctrine.dbal.default_connection"
