# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    obokaman.application.service.user.list:
        class: Obokaman\Application\Service\User\ListUsers
        arguments: ["@obokaman.repository.user"]

    obokaman.application.service.user.add.raw:
        public: false
        class: Obokaman\Application\Service\User\AddUser
        arguments:
            - "@obokaman.repository.user"

    obokaman.application.service.user.add:
        class: Obokaman\Application\Service\EventAwareApplicationServiceDecorator
        arguments:
            - "@obokaman.application.service.user.add.raw"
            - "@obokaman.domain.event_dispatcher"

    obokaman.application.service.user.edit.raw:
        public: false
        class: Obokaman\Application\Service\User\EditUser
        arguments:
            - "@obokaman.repository.user"

    obokaman.application.service.user.edit:
        class: Obokaman\Application\Service\EventAwareApplicationServiceDecorator
        arguments:
            - "@obokaman.application.service.user.edit.raw"
            - "@obokaman.domain.event_dispatcher"

    obokaman.application.service.user.remove.raw:
        public: false
        class: Obokaman\Application\Service\User\RemoveUser
        arguments:
            - "@obokaman.repository.user"

    obokaman.application.service.user.remove:
        class: Obokaman\Application\Service\EventAwareApplicationServiceDecorator
        arguments:
            - "@obokaman.application.service.user.remove.raw"
            - "@obokaman.domain.event_dispatcher"

    obokaman.repository.user:
        class: Obokaman\Infrastructure\Repository\Doctrine\User\UserRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    obokaman.domain.event_dispatcher:
        class: Obokaman\Infrastructure\Event\Symfony\EventDispatcher
        arguments:
            - "@event_dispatcher"
