# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    obokaman.application.service.user.list:
        class: Obokaman\Playground\Application\Service\User\ListUsers
        arguments: ["@obokaman.repository.user"]

    obokaman.application.service.user.add:
        class: Obokaman\Playground\Application\Service\User\AddUser
        arguments:
            - "@obokaman.repository.user"
        tags:
            - { name: command_handler, handles: Obokaman\Playground\Application\Service\User\AddUserCommand }

    obokaman.application.service.user.edit:
        class: Obokaman\Playground\Application\Service\User\EditUser
        arguments:
            - "@obokaman.repository.user"
        tags:
            - { name: command_handler, handles: Obokaman\Playground\Application\Service\User\EditUserCommand }

    obokaman.application.service.user.remove:
        class: Obokaman\Playground\Application\Service\User\RemoveUser
        arguments:
            - "@obokaman.repository.user"
        tags:
            - { name: command_handler, handles: Obokaman\Playground\Application\Service\User\RemoveUserCommand }

    obokaman.repository.user:
        alias: obokaman.repository.orm.user

    obokaman.repository.orm.user:
        public: false
        class: Obokaman\Playground\Infrastructure\Repository\Doctrine\User\UserRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    obokaman.repository.dbal.user:
        public: false
        class: Obokaman\Playground\Infrastructure\Repository\Doctrine\User\UserDbalRepository
        arguments:
            - "@doctrine.dbal.default_connection"

    obokaman.domain.event_dispatcher:
        class: Obokaman\Playground\Infrastructure\MessageBus\Symfony\EventDispatcher
        arguments:
            - "@event_dispatcher"

    obokaman.domain.command_bus:
        class: Obokaman\Playground\Infrastructure\MessageBus\SimpleBus\CommandBus
        arguments:
            - "@command_bus"

    obokaman.domain.command_bus.middleware.event_aware:
        class: Obokaman\Playground\Infrastructure\MessageBus\SimpleBus\EventAwareCommandBusMiddleware
        public: false
        arguments:
            - "@obokaman.domain.event_dispatcher"
        tags:
            - { name: command_bus_middleware, priority: 100 }

    obokaman.domain.command_bus.middleware.db_transaction:
        class: Obokaman\Playground\Infrastructure\MessageBus\SimpleBus\DBTransactionalityCommandBusMiddleware
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_bus_middleware, priority: 100 }
