app_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

app_user_add:
    path:     /add-user
    defaults: { _controller: MainBundle:ManageUser:add }

app_user_remove:
    path:     /remove-user/{user_id}
    defaults: { _controller: MainBundle:ManageUser:remove }

app_user_edit:
    path:     /edit-user/{user_id}/{email}/{name}
    defaults: { _controller: MainBundle:ManageUser:edit }
    methods: ['GET']
