OboBundle\Entity\User:
    type: entity
    repositoryClass: OboBundle\Repository\UserRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        creation_date:
            type: datetime
