Playground\App\Domain\Model\User\User:
    type: entity
    repositoryClass: Playground\App\Infrastructure\Repository\Doctrine\User\UserBaseRepository
    embedded:
        id:
            class: Playground\App\Domain\Model\User\UserId
            columnPrefix: false
        email:
            class: Playground\App\Domain\Model\User\Email
            columnPrefix: false
    fields:
        name:
            type: string
            length: 255
        creation_date:
            type: datetime

    manyToMany:
        skills:
            targetEntity: Playground\App\Domain\Model\Skill\Skill
            joinTable:
                name: user_skill
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referenceColumnName: id
                        unique: true
            cascade:
                - all

