Obokaman\PlaygroundBundle\Entity\Skill:
    type: entity
    repositoryClass: Obokaman\PlaygroundBundle\Repository\SkillRepository
    id:
        skill_id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        description:
            type: string
            length: 255
    manyToOne:
        user:
            targetEntity: Obokaman\PlaygroundBundle\Entity\User
            inversedBy: skills
            joinColumn:
                name: user_id
                referencedColumnName: user_id

