imports:
    - { resource: ../../../../ReadModel/Infrastructure/DependencyInjection/Symfony/services/user.yml }

services:
    ########################
    # Application Services #
    ########################
    user_manager.application.service.user.add.add_user_use_case:
        class: UserManager\Application\Service\User\Add\AddUserUseCase
        arguments:
            - "@user_manager.infrastructure.repository.doctrine.dbal.user.user_repository"
            - "@user_manager.infrastructure.event_dispatcher.symfony"

    user_manager.application.service.user.update.update_user_use_case:
        class: UserManager\Application\Service\User\Update\UpdateUserUseCase
        arguments:
            - "@user_manager.infrastructure.repository.doctrine.dbal.user.user_repository"
            - "@user_manager.infrastructure.event_dispatcher.symfony"

    user_manager.application.service.user.delete.delete_user_use_case:
        class: UserManager\Application\Service\User\Delete\DeleteUserUseCase
        arguments:
            - "@user_manager.infrastructure.repository.doctrine.dbal.user.user_repository"
            - "@user_manager.infrastructure.event_dispatcher.symfony"

    ##################
    # Infrastructure #
    ##################
    user_manager.infrastructure.repository.doctrine.dbal.user.user_repository:
        public: false
        class: UserManager\Infrastructure\Repository\Doctrine\Dbal\User\UserRepository
        arguments: ["@doctrine.dbal.default_connection"]

    user_manager.infrastructure.event_dispatcher.symfony:
        public: false
        class: UserManager\Infrastructure\EventDispatcher\Symfony\EventDispatcher
        arguments: ["@event_dispatcher"]
