services:
    cache.infrastructure.cache.filesystem_cache:
        class: Workshop\CacheBundle\src\Infrastructure\Cache\FilesystemCache
        arguments:
            - "%cache.filesystem.path%"

    #cache.infrastructure.repository.user:
    #    public: false
    #    class: Workshop\CacheBundle\src\Domain\Infrastructure\Repository\UserCacheRepository
    #    decorates: user_bundle.infrastructure.repository.doctrine.dbal.user.user_repository
    #    decoration_inner_name: user_bundle.infrastructure.repository.doctrine.dbal.user.user_repository
    #    arguments:
    #        - "@user_bundle.infrastructure.repository.doctrine.dbal.user.user_repository"
    #        - "@cache.infrastructure.cache.filesystem_cache"
