services:
#    workshop_cache.example:
#        class: workshop\CacheBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    workshop_cache.controller.get_users_service:
        class: workshop\CacheBundle\Controller\GetUsersService
        decorates: workshop_user.controller.get_users_service