services:
    user_manager.infrastructure.cache.filesystem_cache:
        class: UserManager\Infrastructure\Cache\FilesystemCache
        arguments:
            - "%cache.filesystem.path%"

    user_manager.infrastructure.repository.user:
        public: false
        class: UserManager\Infrastructure\Repository\Cache\User\UserCacheRepository
        decorates: user_manager.infrastructure.repository.doctrine.dbal.user.user_repository
        decoration_inner_name: inner.infrastructure.repository.user
        arguments:
            - "@inner.infrastructure.repository.user"
            - "@user_manager.infrastructure.cache.filesystem_cache"

    user_manager.infrastructure.event_subscriber.symfony:
        class: UserManager\Infrastructure\EventSubscriber\Symfony\InvalidateUserCacheSubscriber
        arguments: ["@user_manager.infrastructure.cache.filesystem_cache"]
        tags:
            - { name: kernel.event_subscriber }

