services:
#    workshop_user.example:
#        class: workshop\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    workshop_user.controller.get_users_service:
        class: workshop\UserBundle\Controller\GetUsersService