services:
#    workshop_user.example:
#        class: Workshop\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    workshop_user.controller.get_users_service:
        class: Workshop\UserBundle\Controller\GetUsersService

    workshop_user.controller.add_user_service:
        class: Workshop\UserBundle\Controller\AddUserService
        arguments: ['@event_dispatcher']