Playground\App\Domain\Model\User\User:
    type: entity
    id:
        id:
            type: user_id
    fields:
        email:
            type: email
        name:
            type: string
            length: 255
        creation_date:
            type: datetime
        update_date:
            type: datetime

    manyToMany:
        skills:
            targetEntity: Playground\App\Domain\Model\Skill\Skill
            fetch: EAGER
            joinTable:
                name: user_skill
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referenceColumnName: id
                        unique: true
            cascade:
                - all

