User\Domain\User:
  type: entity
  repositoryClass: User\Infrastructure\Repository\Doctrine\UserRepository
  table: user
  id:
    id:
      type: string
  fields:
    name:
      type: string
    skill:
      type: skill
