Workshop\UserBundle\Entity\DoctrineSkill:
    type: entity
    table: skill
    id:
        skill_id:
            type: string
            generator: { strategy: NONE }
    fields:
        name:
            type: string
            length: 100
        type:
            type: string
            length: 100
    manyToOne:
        user:
            targetEntity: DoctrineUser
            inversedBy: skills
            joinColumn:
                name: user_id
                referencedColumnName: user_id
