UserManager\Domain\Model\User\User:
    type: entity
    table: users
    fields:
        name:
            type: string
        surname:
            type: string
    embedded:
        user_id:
            class: UserManager\Domain\Model\User\ValueObject\UserId
            columnPrefix: false
        email:
            class: UserManager\Domain\Model\Email\Email
            columnPrefix: false


