UserManager\Domain\Model\User\User:
    type: entity
    table: users
    fields:
        name: { type: string }
        surname: { type: string }
    embedded:
        user_id:
            class: UserManager\Domain\Model\User\UserId
            columnPrefix: false
        email:
            class: UserManager\Domain\Model\Email\Email
            columnPrefix: false
        username:
            class: UserManager\Domain\Model\User\Username
            columnPrefix: false
    manyToMany:
        skills:
            targetEntity: Skill
            joinTable:
                name: users_skills
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id
                        unique: true



