services:
    ########################
    # Application Services #
    ########################
    user_manager.read_model.application.service.user.get_all.get_all_users_use_case:
        class: UserManager\ReadModel\Application\Service\User\GetAll\GetAllUsersUseCase
        arguments: ["@user_manager.infrastructure.repository.doctrine.dbal.user.user_repository"]

    user_manager.read_model.application.service.user.get_by_id.get_user_by_id_use_case:
        class: UserManager\ReadModel\Application\Service\User\GetById\GetByIdUseCase
        arguments: ["@user_manager.infrastructure.repository.doctrine.dbal.user.user_repository"]
