services:
    ########################
    # Application Services #
    ########################
    user_manager.read_model.application.service.user.get_all:
        class: UserManager\ReadModel\Application\Service\User\GetAll\GetAllUsers
        arguments:
            - "@user_manager.domain.infrastructure.repository.user"
            - "@user_manager.read_model.application.service.user.get_all.marshaller.user_to_array"

    user_manager.read_model.application.service.user.get_by_id:
        class: UserManager\ReadModel\Application\Service\User\GetById\GetById
        arguments:
            - "@user_manager.domain.infrastructure.repository.user"
            - "@user_manager.read_model.application.service.user.get_by_id.marshaller.user_to_array"

    #Marshallers
    user_manager.read_model.application.service.user.get_by_id.marshaller.user_to_array:
        public: false
        class: UserManager\ReadModel\Application\Service\User\GetById\UserToArrayMarshaller

    user_manager.read_model.application.service.user.get_all.marshaller.user_to_array:
        public: false
        class: UserManager\ReadModel\Application\Service\User\GetAll\UserCollectionToArray
        arguments: ["@user_manager.read_model.application.service.user.get_by_id.marshaller.user_to_array"]
